apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: getting-started
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: getting-started
  rules:
  - host: gsd.minikube.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: getting-started
            port:
              number: 3000