apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  labels:
    app.kubernetes.io/name: getting-started
spec:
  containers:
  - name: 
    image: getting-started
    ports: billybackmanh/getting-started:latest
      - containerPort: 3000
        name: getting-started
