apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
  labels:
    app: getting-started
spec:
  replicas: 1
  containers:
  - name: getting-started
    image: billybackmanh/getting-started:latest
    ports:
    - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  name: getting-started
  labels:
    app.kubernetes.io/name: getting-started
